# Generated by Django 5.2.15 on 2026-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_migration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credentialversion',
            name='legacy_credver_unique',
        ),
        migrations.RemoveConstraint(
            model_name='legacyconfirmation',
            name='legacy_confirmation_unique',
        ),
        migrations.AlterField(
            model_name='credentialversion',
            name='changed_by',
            field=models.UUIDField(blank=True, help_text='Actor who caused this version to be created.', null=True),
        ),
        migrations.AlterField(
            model_name='credentialversion',
            name='credential_id',
            field=models.UUIDField(db_index=True, help_text='Credential.id this version belongs to.'),
        ),
        migrations.AlterField(
            model_name='credentialversion',
            name='payload_snapshot',
            field=models.JSONField(help_text='Complete payload dict at this version.'),
        ),
        migrations.AlterField(
            model_name='credentialversion',
            name='version',
            field=models.PositiveIntegerField(help_text='Monotonically increasing version number (1 = original).'),
        ),
        migrations.AlterField(
            model_name='legacybatch',
            name='affidavit_ref',
            field=models.CharField(blank=True, help_text='Reference to the notarised institution affidavit (F09-02 requirement).', max_length=255),
        ),
        migrations.AlterField(
            model_name='legacybatch',
            name='affidavit_verified',
            field=models.BooleanField(default=False, help_text='Registrar must verify affidavit before batch may proceed to Live.'),
        ),
        migrations.AlterField(
            model_name='legacybatch',
            name='batch_ref',
            field=models.CharField(help_text='EVS-generated batch reference for the institution officer.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='legacybatch',
            name='file_sha256',
            field=models.CharField(help_text='SHA-256 of the uploaded file — immutable once set.', max_length=64),
        ),
        migrations.AlterField(
            model_name='legacybatch',
            name='uploaded_by',
            field=models.UUIDField(help_text='keycloak_sub of the institution officer.'),
        ),
        migrations.AlterField(
            model_name='legacyconfirmation',
            name='credential_id',
            field=models.UUIDField(db_index=True, help_text='Credential.id of the legacy record being confirmed.'),
        ),
        migrations.AlterField(
            model_name='legacyconfirmation',
            name='decided_by',
            field=models.UUIDField(help_text='keycloak_sub of the institution officer.'),
        ),
        migrations.AlterField(
            model_name='migrationauditreport',
            name='audit_chain_ref',
            field=models.CharField(blank=True, help_text='System 22 AuditEvent.id for the final dual-signed state.', max_length=100),
        ),
        migrations.AlterField(
            model_name='migrationauditreport',
            name='report_payload',
            field=models.JSONField(default=dict, help_text='Full report content: counts, parity checks, anomaly summary.'),
        ),
        migrations.AlterField(
            model_name='migrationwave',
            name='confirmation_deadline',
            field=models.DateTimeField(help_text='Institution must confirm all records before this deadline (14-day window).'),
        ),
        migrations.AlterField(
            model_name='migrationwave',
            name='institution_id',
            field=models.UUIDField(db_index=True, help_text='Institution whose historical records this wave covers.'),
        ),
        migrations.AlterField(
            model_name='migrationwave',
            name='name',
            field=models.CharField(help_text="Human-readable wave identifier, e.g. 'KNUST-2010-2015'.", max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='credentialversion',
            unique_together={('credential_id', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='legacyconfirmation',
            unique_together={('batch', 'credential_id')},
        ),
    ]
