# Generated by Django 6.0.5 on 2026-06-15 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short code, e.g. GSL, KSL, GIMPA.', max_length=20, unique=True)),
                ('accreditation_number', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'institutions_institutionmaster',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GraduationCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('session', models.CharField(blank=True, help_text="Human-readable label, e.g. 'July 2024'.", max_length=50)),
                ('submission_deadline', models.DateField(help_text='Date by which the institution must submit all credential data.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('closed', 'Closed'), ('overdue', 'Overdue')], db_index=True, default='open', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.UUIDField(blank=True, help_text='UserProfile.id of the institution officer who finalised submission.', null=True)),
                ('sla_d20_notified', models.BooleanField(default=False, help_text='True once the D-20 (20 days remaining) reminder has been sent.')),
                ('sla_d7_notified', models.BooleanField(default=False, help_text='True once the D-7 (7 days remaining) reminder has been sent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='institutions.institutionmaster')),
            ],
            options={
                'db_table': 'institutions_graduationcycle',
                'ordering': ['-year', 'institution__code'],
            },
        ),
        migrations.CreateModel(
            name='SlaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('d20_reminder', 'D-20 Reminder Sent'), ('d7_reminder', 'D-7 Reminder Sent'), ('overdue_escalation', 'Overdue Escalation'), ('submission_received', 'Submission Received')], db_index=True, max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_events', to='institutions.graduationcycle')),
            ],
            options={
                'db_table': 'institutions_slaevent',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='graduationcycle',
            index=models.Index(fields=['status', 'submission_deadline'], name='institution_status_a74560_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='graduationcycle',
            unique_together={('institution', 'year', 'session')},
        ),
    ]
