# Generated by Django 6.0.5 on 2026-06-15 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSchemaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_id', models.CharField(db_index=True, help_text="Logical schema name, e.g. 'gsl-llb', 'gsl-bl'.", max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, help_text="Human-readable label, e.g. 'GSL LLB 2024'.", max_length=255)),
                ('schema_json', models.JSONField(help_text='JSON Schema (draft-07) used to validate credential payloads.')),
                ('required_fields', models.JSONField(default=list, help_text='Ordered list of field names that must be present in every record.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registry_credentialschemaversion',
                'ordering': ['schema_id', '-version'],
                'unique_together': {('schema_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_ref', models.CharField(db_index=True, help_text='Human-readable reference, e.g. GSL/2024/LLB/001234.', max_length=150, unique=True)),
                ('institution_id', models.UUIDField(db_index=True, help_text='InstitutionMaster.id — FK enforced at application layer (cross-app).')),
                ('graduation_cycle_id', models.UUIDField(blank=True, db_index=True, help_text='GraduationCycle.id — FK enforced at application layer.', null=True)),
                ('candidate_id', models.UUIDField(blank=True, db_index=True, help_text='UserProfile.id if the candidate has an EVS account.', null=True)),
                ('payload', models.JSONField(help_text='Canonical credential payload (sorted keys, NFC strings).')),
                ('sha256_hash', models.CharField(db_index=True, help_text='SHA-256 hex of canonical JSON payload — tamper evidence anchor.', max_length=64, unique=True)),
                ('qr_payload', models.TextField(blank=True, help_text='Signed JWT embedded in the QR code.')),
                ('qr_url', models.URLField(blank=True, help_text='https://evs.clet.gov.gh/verify/<uuid>?token=<jwt>', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('quarantined', 'Quarantined — under review')], db_index=True, default='active', max_length=15)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('revoked_by', models.UUIDField(blank=True, null=True)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, help_text='BatchIngest.id that created this record.', null=True)),
                ('integrity_checked_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_ok', models.BooleanField(blank=True, help_text='Set by the nightly integrity sweep task.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='registry.credentialschemaversion')),
            ],
            options={
                'db_table': 'registry_credential',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchIngest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('graduation_cycle_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('submitted_by', models.UUIDField(blank=True, help_text='UserProfile.id of the institution officer.', null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hex of the uploaded file.', max_length=64)),
                ('file_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(default=list, help_text='List of {row, ref, error} for each failed record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_ingests', to='registry.credentialschemaversion')),
            ],
            options={
                'db_table': 'registry_batchingest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevocationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revoked_by', models.UUIDField(help_text='UserProfile.id of the revoking officer.')),
                ('reason', models.TextField()),
                ('revoked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocations', to='registry.credential')),
            ],
            options={
                'db_table': 'registry_revocationrecord',
                'ordering': ['-revoked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['institution_id', 'status'], name='registry_cr_institu_688af6_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['graduation_cycle_id', 'status'], name='registry_cr_graduat_eb503a_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['candidate_id'], name='registry_cr_candida_0c552f_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['integrity_ok', 'status'], name='registry_cr_integri_68b79e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchingest',
            index=models.Index(fields=['institution_id', 'status'], name='registry_ba_institu_1b9dd9_idx'),
        ),
    ]
