# Generated by Django 5.2.15 on 2026-06-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_pii_columns_transaction_id_deprecated_at_integrityrun'),
        ('registry', '0003_integrity_run'),
        ('registry', '0003_revocationrecord_source_signature_ref'),
    ]

    operations = [
    ]
