# Generated by Django 5.2.15 on 2026-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_pii_columns_transaction_id_deprecated_at_integrityrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='credential',
            new_name='registry_cr_graduat_e03e84_idx',
            old_name='cred_grad_idx_num_idx',
        ),
        migrations.RenameIndex(
            model_name='integrityrun',
            new_name='registry_in_status_232d2a_idx',
            old_name='registry_integrun_status_idx',
        ),
        migrations.RenameIndex(
            model_name='integrityrun',
            new_name='registry_in_sweep_t_b90d19_idx',
            old_name='registry_integrun_type_idx',
        ),
        migrations.AlterField(
            model_name='credential',
            name='legacy',
            field=models.BooleanField(db_index=True, default=False, help_text='True if migrated from a legacy system (Phase 8).'),
        ),
    ]
