# Generated by Django 6.0.5 on 2026-06-15 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCredentialApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Human-readable reference, e.g. FCA-2026-0001.', max_length=30, unique=True)),
                ('applicant_sub', models.UUIDField(db_index=True, help_text='Keycloak subject of the applicant.')),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_name', models.CharField(max_length=200)),
                ('foreign_institution', models.CharField(max_length=255)),
                ('foreign_country', models.CharField(max_length=100)),
                ('foreign_degree', models.CharField(max_length=255)),
                ('graduation_year', models.SmallIntegerField()),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('documents_pending', 'Documents Pending'), ('triaged', 'Triaged by Registrar'), ('routed_internal', 'Routed to Internal Assessor'), ('routed_gtec', 'Routed to GTEC'), ('assessor_assigned', 'Assessor Assigned'), ('under_review', 'Under Review'), ('recommendation_made', 'Recommendation Made'), ('registrar_reviewed', 'Registrar Reviewed'), ('dg_pending', 'Awaiting DG Signature'), ('dg_signed', 'DG Signed — Decision Issued'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=25)),
                ('route', models.CharField(blank=True, choices=[('internal', 'Internal Assessor'), ('gtec', 'GTEC'), ('', 'Not yet routed')], db_index=True, max_length=10)),
                ('outcome', models.CharField(blank=True, choices=[('accepted', 'Accepted — Equivalent'), ('rejected', 'Rejected — Not Equivalent'), ('withdrawn', 'Withdrawn by Applicant'), ('', 'Pending')], max_length=12)),
                ('triaged_by', models.UUIDField(blank=True, help_text='Registrar keycloak_sub.', null=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('assessor_sub', models.UUIDField(blank=True, db_index=True, help_text='Assigned assessor keycloak_sub (Internal or GTEC).', null=True)),
                ('assessor_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('sla_due_at', models.DateTimeField(blank=True, help_text='Overall application SLA deadline (28 calendar days from triaged_at).', null=True)),
                ('dg_sub', models.UUIDField(blank=True, help_text='Director-General keycloak_sub.', null=True)),
                ('dg_signed_at', models.DateTimeField(blank=True, null=True)),
                ('dg_signature_ref', models.CharField(blank=True, help_text='HSM key ID of the DG signing key used.', max_length=100)),
                ('decision_sha256', models.CharField(blank=True, help_text='SHA-256 of the canonical decision JSON. Set at DG sign.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fca_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage', 'route', 'created_at'], name='fca_applica_stage_94f9cc_idx'), models.Index(fields=['applicant_sub', 'stage'], name='fca_applica_applica_7a5c8f_idx'), models.Index(fields=['assessor_sub', 'stage'], name='fca_applica_assesso_0cc7b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquivalenceRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessor_sub', models.UUIDField()),
                ('recommendation', models.CharField(choices=[('equivalent', 'Equivalent — recommend acceptance'), ('not_equivalent', 'Not equivalent — recommend rejection'), ('partial_equivalent', 'Partially equivalent — conditional acceptance')], max_length=20)),
                ('rationale', models.TextField(help_text='Detailed reasoning. Preserved in the tamper-evident record.')),
                ('accreditation_ok', models.BooleanField(help_text="True when the institution's accreditation has been confirmed.")),
                ('content_match_pct', models.SmallIntegerField(blank=True, help_text='Estimated % content overlap with GSL LLB curriculum.', null=True)),
                ('conditions', models.TextField(blank=True, help_text='Any conditions attached to a partial_equivalent recommendation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='foreign_credentials.foreigncredentialapplication')),
            ],
            options={
                'db_table': 'fca_equivalencerecommendation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DGDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dg_sub', models.UUIDField(help_text='keycloak_sub of the Director-General.')),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted — Equivalent'), ('rejected', 'Rejected — Not Equivalent'), ('withdrawn', 'Withdrawn by Applicant'), ('', 'Pending')], max_length=12)),
                ('decision_text', models.TextField(help_text='Official decision text — becomes part of the signed record.')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hsm_key_id', models.CharField(help_text='HSM key ID (HsmKey.key_id) used to sign this decision.', max_length=100)),
                ('signature_b64', models.TextField(help_text='Base64-encoded RSA-PSS signature over decision_sha256.')),
                ('decision_sha256', models.CharField(help_text='SHA-256 of the canonical decision JSON (sorted keys, NFC, UTF-8).', max_length=64)),
                ('anchor_ref', models.CharField(blank=True, help_text='System 22 (CALS) anchor reference for the integrity chain.', max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dg_decision', to='foreign_credentials.foreigncredentialapplication')),
            ],
            options={
                'db_table': 'fca_dgdecision',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('degree_certificate', 'Degree Certificate'), ('transcript', 'Academic Transcript'), ('course_syllabus', 'Course Syllabus'), ('identity', 'Identity Document'), ('translation', 'Certified Translation'), ('other', 'Other')], max_length=20)),
                ('file_sha256', models.CharField(help_text='SHA-256 links to DocumentVaultObject; file stored there.', max_length=64)),
                ('original_filename_hash', models.CharField(blank=True, max_length=64)),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_by', models.UUIDField(help_text='keycloak_sub.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, help_text='True once a Registrar has verified the document is authentic.')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='foreign_credentials.foreigncredentialapplication')),
            ],
            options={
                'db_table': 'fca_applicationdocument',
                'ordering': ['doc_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(max_length=25)),
                ('to_stage', models.CharField(max_length=25)),
                ('actor_sub', models.UUIDField(help_text='keycloak_sub of the actor.')),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='foreign_credentials.foreigncredentialapplication')),
            ],
            options={
                'db_table': 'fca_workflowtransition',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='FcaSlaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=25)),
                ('event', models.CharField(choices=[('entered', 'Stage entered'), ('breached', 'SLA breached'), ('escalated', 'Escalated to Secretariat'), ('resolved', 'Stage resolved')], max_length=12)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_sub', models.UUIDField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_events', to='foreign_credentials.foreigncredentialapplication')),
            ],
            options={
                'db_table': 'fca_slaevent',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['application', 'stage', 'occurred_at'], name='fca_slaeven_applica_5762d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessor_sub', models.UUIDField(db_index=True)),
                ('task', models.CharField(choices=[('accreditation', 'Accreditation Review'), ('content', 'Content Review')], max_length=15)),
                ('assigned_by', models.UUIDField(help_text='Registrar keycloak_sub.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sla_due_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='foreign_credentials.foreigncredentialapplication')),
            ],
            options={
                'db_table': 'fca_assessorassignment',
                'ordering': ['sla_due_at'],
                'unique_together': {('application', 'assessor_sub', 'task')},
            },
        ),
    ]
