# Generated by Django 6.0.5 on 2026-06-15 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id_claimed', models.UUIDField(db_index=True, help_text='The UUID from the URL path — not yet validated at record creation.')),
                ('result', models.CharField(choices=[('verified', 'Verified'), ('revoked', 'Revoked'), ('quarantined', 'Quarantined'), ('not_found', 'Not Found'), ('tampered', 'Tampered — integrity failure'), ('token_invalid', 'Token Invalid'), ('token_expired', 'Token Expired')], db_index=True, max_length=20)),
                ('verifier_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verifier_user_agent', models.TextField(blank=True)),
                ('verifier_id', models.UUIDField(blank=True, db_index=True, help_text='UserProfile.id if the verifier was authenticated.', null=True)),
                ('jwt_kid', models.CharField(blank=True, help_text='Key ID from the QR JWT header.', max_length=100)),
                ('verification_ms', models.PositiveIntegerField(blank=True, help_text='End-to-end verification latency in milliseconds. Target: ≤2000 ms.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('credential', models.ForeignKey(blank=True, help_text='Null when the credential was not found or token was invalid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_sessions', to='registry.credential')),
            ],
            options={
                'db_table': 'verification_verificationsession',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['result', 'created_at'], name='verificatio_result_1aeabd_idx'), models.Index(fields=['credential_id_claimed', 'created_at'], name='verificatio_credent_5dd6cd_idx')],
            },
        ),
    ]
