# Generated by Django 6.0.5 on 2026-06-15 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVaultObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('uploaded_by', models.UUIDField(blank=True, help_text='keycloak_sub of the Verifier who uploaded the file.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateField(help_text='File must be preserved until this date.')),
                ('encryption_kid', models.CharField(blank=True, help_text='HSM key ID used to encrypt the stored blob.', max_length=100)),
                ('tamper_flag', models.BooleanField(default=False, help_text='Set when a verification of this file returned Tampered.')),
                ('original_filename_hash', models.CharField(blank=True, help_text='SHA-256 of the original filename (not the file itself); PII-safe.', max_length=64)),
                ('virus_clean', models.BooleanField(default=False, help_text='True once the AV scanner returned clean.')),
            ],
            options={
                'db_table': 'verification_documentvaultobject',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfSignatureOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_subject', models.TextField(help_text='Distinguished Name of the signing certificate.')),
                ('signing_time', models.DateTimeField(blank=True, null=True)),
                ('profile', models.CharField(choices=[('pades_bt', 'PAdES B-T'), ('pades_blt', 'PAdES B-LT'), ('pades_blta', 'PAdES B-LTA'), ('pkcs7', 'PKCS#7 Detached')], max_length=15)),
                ('integrity_ok', models.BooleanField(help_text='True when the PDF byte-range hash matches the embedded signature.')),
                ('chain_ok', models.BooleanField(help_text='True when the certificate chain validates up to a trust anchor.')),
                ('revocation_status', models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('revoked', 'Revoked'), ('unchecked', 'Unchecked — OCSP/CRL unreachable')], max_length=10)),
                ('timestamp_ok', models.BooleanField(blank=True, help_text='True when the embedded timestamp token validates. Null for B-T profiles.', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Machine-readable failure code if any check failed.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_pdfsignatureoutcome',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ca_name', models.CharField(max_length=255)),
                ('ca_certificate_pem', models.TextField(help_text='PEM-encoded CA certificate.')),
                ('ocsp_endpoint', models.URLField(blank=True)),
                ('crl_endpoint', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10)),
                ('added_by', models.UUIDField(blank=True, help_text='keycloak_sub of the Administrator.', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_change_ref', models.CharField(blank=True, help_text='AuditEvent id of the signed configuration-change record.', max_length=100)),
            ],
            options={
                'db_table': 'verification_trustanchor',
                'ordering': ['ca_name'],
            },
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='channel',
            field=models.CharField(choices=[('qr_scan', 'QR Scan'), ('pdf', 'PDF Upload'), ('uploaded_qr', 'Uploaded-QR'), ('waec', 'WAEC'), ('faculty', 'Faculty Connector'), ('manual', 'Manual')], db_index=True, default='qr_scan', max_length=15),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of uploaded PDF/image; links session to DocumentVaultObject.', max_length=64),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='result_detail',
            field=models.CharField(blank=True, help_text='Machine-readable detail code, e.g. BYTE_RANGE_INTEGRITY_FAILURE.', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationsession',
            name='credential_id_claimed',
            field=models.UUIDField(blank=True, db_index=True, help_text='The UUID from the URL path or PDF metadata — not yet validated at record creation.', null=True),
        ),
        migrations.AlterField(
            model_name='verificationsession',
            name='result',
            field=models.CharField(choices=[('verified', 'Verified'), ('revoked', 'Revoked'), ('quarantined', 'Quarantined'), ('not_found', 'Not Found'), ('tampered', 'Tampered — integrity failure'), ('token_invalid', 'Token Invalid'), ('token_expired', 'Token Expired'), ('invalid_signature', 'Invalid Signature'), ('untrusted_issuer', 'Untrusted Issuer'), ('invalid_qr', 'Invalid QR Code'), ('manual_pending', 'Queued for Manual Verification')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationsession',
            name='verification_ms',
            field=models.PositiveIntegerField(blank=True, help_text='End-to-end verification latency in milliseconds.', null=True),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['channel', 'result', 'created_at'], name='verificatio_channel_874937_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['file_sha256'], name='verificatio_file_sh_d407e3_idx'),
        ),
        migrations.AddField(
            model_name='pdfsignatureoutcome',
            name='verification_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_outcomes', to='verification.verificationsession'),
        ),
        migrations.AddField(
            model_name='pdfsignatureoutcome',
            name='signer_ca',
            field=models.ForeignKey(blank=True, help_text='The trust anchor whose chain this signature validated against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_outcomes', to='verification.trustanchor'),
        ),
    ]
