# Generated by Django 5.2.15 on 2026-06-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_documentvaultobject_pdfsignatureoutcome_trustanchor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationsession',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Client-supplied device fingerprint for fraud correlation.', max_length=255),
        ),
    ]
