# Generated by Django 5.2.15 on 2026-06-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_documentvaultobject_pdfsignatureoutcome_trustanchor_and_more'),
        ('verification', '0002_verification_session_v2'),
    ]

    operations = [
    ]
