# Generated by Django 6.0.5 on 2026-06-15 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HsmKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid', models.CharField(db_index=True, help_text='Key identifier — included in JWT header and JWKS response.', max_length=100, unique=True)),
                ('algorithm', models.CharField(choices=[('ES256', 'ES256 — ECDSA P-256'), ('RS256', 'RS256 — RSA-PKCS1v1.5 2048'), ('EdDSA', 'EdDSA — Ed25519'), ('HS256', 'HS256 — HMAC-SHA256 (dev only)')], max_length=10)),
                ('purpose', models.CharField(choices=[('qr_jwt_sign', 'QR JWT Signing'), ('dg_sign', 'Director-General Credential Signing'), ('credential_sign', 'Credential Batch Signing'), ('hmac_relay', 'HMAC Inter-Service Relay')], db_index=True, max_length=20)),
                ('public_key_pem', models.TextField(blank=True, help_text='PEM-encoded public key (stored here; private key stays in HSM/env).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, help_text='Null = no expiry defined at creation time.', null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hsm_hsmkey',
                'ordering': ['-created_at'],
            },
        ),
    ]
