# Generated by Django 5.2.15 on 2026-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsmkey',
            name='purpose',
            field=models.CharField(choices=[('qr_jwt_sign', 'QR JWT Signing'), ('dg_sign', 'Director-General Credential Signing'), ('credential_sign', 'Credential Batch Signing'), ('revocation_list_integrity', 'Revocation List Integrity')], db_index=True, max_length=50),
        ),
    ]
