# Generated by Django 5.2.15 on 2026-06-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_roles_rename_and_add_missing'),
        ('users', '0005_seed_phase9_10_permissions'),
    ]

    operations = [
    ]
