# Generated by Django 6.0.5 on 2026-06-15 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('waec', 'WAEC'), ('faculty', 'Law Faculty'), ('gtec', 'GTEC'), ('nlems', 'NLEMS'), ('nbes', 'NBES')], db_index=True, max_length=10)),
                ('sandbox_endpoint', models.URLField(blank=True)),
                ('production_endpoint', models.URLField(blank=True)),
                ('lifecycle_state', models.CharField(choices=[('onboarding', 'Onboarding'), ('sandbox_validated', 'Sandbox Validated'), ('production_live', 'Production Live'), ('suspended', 'Suspended'), ('decommissioned', 'Decommissioned')], db_index=True, default='onboarding', max_length=25)),
                ('contact_owner', models.EmailField(blank=True, max_length=254)),
                ('current_credential_id', models.UUIDField(blank=True, help_text='FK to ConnectorCredential.id of the active credential.', null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('latency_p95_threshold_ms', models.PositiveIntegerField(default=10000, help_text='Circuit-breaker opens when p95 latency exceeds this value over the rolling window.')),
                ('sandbox_validated_at', models.DateTimeField(blank=True, null=True)),
                ('sandbox_validation_ref', models.CharField(blank=True, help_text='AuditEvent id of the sandbox validation run.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'connectors_connector',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaecRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_number', models.CharField(max_length=30)),
                ('year_of_completion', models.SmallIntegerField()),
                ('examination_series', models.CharField(help_text='Private or Regular.', max_length=10)),
                ('dob_masked', models.CharField(help_text='Date of birth stored as MM/****  (day and year masked for PII compliance).', max_length=20)),
                ('request_payload_hash', models.CharField(help_text='SHA-256 of the outbound WAEC request for evidentiary linkage.', max_length=64)),
                ('response_status', models.CharField(choices=[('verified', 'Verified – Matches Official Record'), ('not_found', 'Not Found'), ('mismatch', 'Mismatch in Details'), ('api_error', 'API Error'), ('queued', 'Queued for Manual Verification')], db_index=True, max_length=10)),
                ('sanitised_response', models.JSONField(blank=True, help_text='Subset of the WAEC response permitted by the sanitisation rules.', null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('queued_flag', models.BooleanField(default=False, help_text='True when circuit-breaker was open and the request was queued.')),
                ('result_id', models.UUIDField(blank=True, help_text='VerificationSession.id minted for this verification.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'connectors_waecrequests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('oauth', 'OAuth 2.0'), ('api_key', 'API Key'), ('mtls', 'mTLS')], max_length=10)),
                ('value_kid', models.CharField(help_text='HSM key ID for stored credential value. Plaintext never stored.', max_length=100)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Null means no expiry configured — prefer explicit expiry.', null=True)),
                ('rotation_reason', models.CharField(blank=True, max_length=255)),
                ('rotated_by', models.UUIDField(blank=True, help_text='keycloak_sub of the Administrator who issued this credential.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='connectors.connector')),
            ],
            options={
                'db_table': 'connectors_connectorcredential',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakerState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('closed', 'Closed — healthy'), ('half_open', 'Half-open — probing'), ('open', 'Open — failing fast')], db_index=True, max_length=10)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, help_text='Why the breaker transitioned to this state.', max_length=255)),
                ('error_rate_pct', models.FloatField(blank=True, help_text='Error rate % over the rolling window that triggered the open transition.', null=True)),
                ('consecutive_probe_successes', models.PositiveSmallIntegerField(default=0, help_text='Successful half-open probes before auto-close.')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaker_states', to='connectors.connector')),
            ],
            options={
                'db_table': 'connectors_breakerstate',
                'ordering': ['-since'],
                'indexes': [models.Index(fields=['connector', 'state', 'since'], name='connectors__connect_a11ac3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectorHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('probe_result', models.CharField(choices=[('ok', 'OK'), ('degraded', 'Degraded'), ('down', 'Down')], max_length=10)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='connectors.connector')),
            ],
            options={
                'db_table': 'connectors_connectorhealth',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['connector', 'ts'], name='connectors__connect_c15b3e_idx'), models.Index(fields=['connector', 'probe_result', 'ts'], name='connectors__connect_71f85c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManualQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_payload', models.JSONField(help_text='Sanitised request payload — PII stripped per retention rules.')),
                ('consumer_id', models.CharField(blank=True, help_text='System identifier of the originating consumer (e.g. NLEMS, NBES).', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed by Registrar'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Secretariat')], db_index=True, default='pending', max_length=12)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sla_due_at', models.DateTimeField(db_index=True, help_text='SLA deadline — items past this date escalate automatically.')),
                ('claimed_by', models.UUIDField(blank=True, help_text='keycloak_sub of the Registrar who claimed this item.', null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_status', models.CharField(blank=True, help_text='e.g. verified, not_found, mismatch — same vocabulary as VerificationSession.result.', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('result_id', models.UUIDField(blank=True, help_text='VerificationSession.id minted when resolved.', null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='connectors.connector')),
            ],
            options={
                'db_table': 'connectors_manualqueueitem',
                'ordering': ['sla_due_at'],
                'indexes': [models.Index(fields=['status', 'sla_due_at'], name='connectors__status_3fd65a_idx'), models.Index(fields=['connector', 'status'], name='connectors__connect_e90794_idx')],
            },
        ),
    ]
