# Generated by Django 6.0.5 on 2026-06-15 16:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('old_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('source_system', models.CharField(default='evs', max_length=20)),
                ('chain_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'db_table': 'audit_auditevent',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyHashAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('head_event_id', models.UUIDField(blank=True, null=True)),
                ('head_hash', models.CharField(max_length=64)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('exported_to_s22_at', models.DateTimeField(blank=True, null=True)),
                ('anchor_ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Daily Hash Anchor',
                'db_table': 'audit_dailyhashanchor',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('traceparent', models.CharField(blank=True, max_length=255, null=True)),
                ('tracestate', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_outboxevent',
                'indexes': [models.Index(fields=['published', 'created_at'], name='audit_outbo_publish_d19fd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('category', models.CharField(choices=[('auth_token_invalid', 'auth_token_invalid'), ('auth_token_expired', 'auth_token_expired'), ('auth_audience_mismatch', 'auth_audience_mismatch'), ('authz_denied', 'authz_denied'), ('step_up_denied', 'step_up_denied'), ('throttle_applied', 'throttle_applied'), ('ip_blocked', 'ip_blocked'), ('anomaly_detected', 'anomaly_detected'), ('role_conflict_in_jwt', 'role_conflict_in_jwt'), ('fraud_flag_raised', 'fraud_flag_raised')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('high', 'high')], default='warning', max_length=10)),
                ('indicators', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_securityevent',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['category', 'occurred_at'], name='audit_secur_categor_cedfec_idx'), models.Index(fields=['ip_address', 'occurred_at'], name='audit_secur_ip_addr_e620d8_idx')],
            },
        ),
    ]
