# Generated by Django 5.2.15 on 2026-06-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audit_immutability_trigger'),
        ('audit', '0003_seed_go_live_gates'),
    ]

    operations = [
    ]
