# Generated by Django 5.2.15 on 2026-06-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_seed_go_live_gates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailycommitment',
            new_name='audit_daily_date_accf8e_idx',
            old_name='audit_daily_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='exportrequest',
            new_name='audit_expor_actor_i_73f3b3_idx',
            old_name='audit_export_actor_created_idx',
        ),
        migrations.RenameIndex(
            model_name='exportrequest',
            new_name='audit_expor_status_324f13_idx',
            old_name='audit_export_status_created_idx',
        ),
    ]
