# Generated by Django 5.2.15 on 2026-06-22 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fraudflag',
            new_name='fraud_fraud_severit_c1ffda_idx',
            old_name='fraud_flag_sev_status_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudflag',
            new_name='fraud_fraud_status_19b408_idx',
            old_name='fraud_flag_status_esc_idx',
        ),
        migrations.RenameIndex(
            model_name='fraudflag',
            new_name='fraud_fraud_flag_ty_3bb22f_idx',
            old_name='fraud_flag_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='watchlistentry',
            new_name='fraud_watch_applica_124c76_idx',
            old_name='fraud_watchlist_appl_idx',
        ),
        migrations.AlterField(
            model_name='flagaction',
            name='actor_user_id',
            field=models.UUIDField(blank=True, help_text='keycloak_sub of the acting user; null for system actions.', null=True),
        ),
        migrations.AlterField(
            model_name='flagaction',
            name='audit_chain_ref',
            field=models.CharField(blank=True, help_text='AuditEvent.id anchored to System 22.', max_length=100),
        ),
        migrations.AlterField(
            model_name='flagaction',
            name='payload',
            field=models.JSONField(default=dict, help_text='Context: old/new status, justification, escalation target, etc.'),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='applicant_ids',
            field=models.JSONField(default=list, help_text='List of applicant keycloak_sub strings.'),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='audit_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the immutable audit chain entry anchored to System 22.', max_length=64),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='credential_ids',
            field=models.JSONField(default=list, help_text='List of Credential UUID strings involved in this flag.'),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When the auto-escalation notification was sent.', null=True),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='evidence_bundle_uri',
            field=models.CharField(blank=True, help_text='URI of the signed, downloadable evidence bundle.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='evidence_payload',
            field=models.JSONField(default=dict, help_text='Linked records, diff highlights, rule context.'),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='fuzzy_similarity_score',
            field=models.FloatField(blank=True, help_text='Levenshtein similarity ratio for fuzzy_identity flags.', null=True),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='resolution_justification',
            field=models.TextField(blank=True, help_text='Mandatory ≥30-word justification. Normalised before word-count check.'),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='resolver_id',
            field=models.UUIDField(blank=True, help_text='keycloak_sub of the Registrar who resolved this flag.', null=True),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='rule',
            field=models.ForeignKey(blank=True, help_text='Set when flag_type is rule_match.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flags', to='fraud_detection.ruledefinition'),
        ),
        migrations.AlterField(
            model_name='ruledefinition',
            name='approved_by',
            field=models.UUIDField(blank=True, help_text='First approver — must differ from created_by.', null=True),
        ),
        migrations.AlterField(
            model_name='ruledefinition',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='keycloak_sub of the authoring Administrator.', null=True),
        ),
        migrations.AlterField(
            model_name='ruledefinition',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, help_text='Deprecated rules are retained for historical re-evaluation.', null=True),
        ),
        migrations.AlterField(
            model_name='ruledefinition',
            name='effective_from',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Rule activates at the next scheduled sweep at or after this time.', null=True),
        ),
        migrations.AlterField(
            model_name='ruledefinition',
            name='evidence_template',
            field=models.TextField(blank=True, help_text='Narrative template for the evidence package.'),
        ),
        migrations.AlterField(
            model_name='ruledefinition',
            name='second_approver',
            field=models.UUIDField(blank=True, help_text='Second approver — activation requires both distinct approvers.', null=True),
        ),
        migrations.AlterField(
            model_name='rulerun',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='BatchIngest.id for post-ingest trigger.', null=True),
        ),
        migrations.AlterField(
            model_name='rulerun',
            name='triggered_by',
            field=models.UUIDField(blank=True, help_text='Actor keycloak_sub for on-demand runs; null for scheduled.', null=True),
        ),
        migrations.AlterField(
            model_name='watchlistentry',
            name='added_by',
            field=models.UUIDField(help_text='keycloak_sub of the actor.'),
        ),
        migrations.AlterField(
            model_name='watchlistentry',
            name='applicant_id',
            field=models.UUIDField(db_index=True, help_text='Keycloak subject UUID of the flagged applicant.'),
        ),
    ]
